### ISSUE TITLE
Flip & Jump!

### ISSUE THREAD

**Issue by ManzDev** [ireade/caniuse-embed#1]
I think that is a "responsive" text reflow problem... or Chrome bug?

![caniuse-flip](https://cloud.githubusercontent.com/assets/1507150/14185244/fab5eb0a-f770-11e5-88a8-61030ed476fa.gif)

**Comment by ireade** [comment]
Thanks for letting me know about this. I just need leave a bit more breathing room in the height of the iframe container.

**Comment by ireade** [comment]
@ManzDev I just pushed an update, can you double check if you're still experiencing this issue?

**Comment by ManzDev** [comment]
@ireade fixed! Thanks!
