### ISSUE TITLE
Cannot find https://caniuse.com/#feat=mdn-javascript_statements_import_meta at embed version

### ISSUE THREAD

**Issue by Jack-Works** [ireade/caniuse-embed#11]

**Comment by ireade** [comment]
Hi @Jack-Works  ! It's because that is an MDN feature, it isn't actually from caniuse dataset. I'm gonna look into how to add the MDN features in the future

**Comment by nhoizey** [comment]
Got the same issue with `mdn-css_properties_clip-path_basic_shape`… 😥
