### ISSUE TITLE
Live and static images generated with huge white space at the bottom

### ISSUE THREAD

**Issue by neluzhin** [ireade/caniuse-embed#13]
Image example: 

![Image with huge bottom padding bug example](https://res.cloudinary.com/ireaderinokun/image/upload/v1/caniuse-embed/all/css-all.webp)

https://res.cloudinary.com/ireaderinokun/image/upload/v1/caniuse-embed/all/css-all.webp

**Comment by ireade** [comment]
Hey @neluzhin !

So I've recently solved this for the live images (make sure you're using the caniuse.bitsofco.de URL and not the cloudinary URL otherwise the image won't be updated)

![](https://caniuse.bitsofco.de/image/css-all.png)

I'm still working on fixing this for the static images

**Comment by ireade** [comment]
@neluzhin Finally got this fixed!
