### ISSUE TITLE
Adding Chosen or Select2 for selecting feature in Embed Generator

### ISSUE THREAD

**Issue by ariona** [ireade/caniuse-embed#2]
It will be much easier to search a feature in generator if the select is enhanced with Chosen or Select2 with Search feature.

**Comment by ireade** [comment]
Thanks for the suggestion, I will work on this

**Comment by ireade** [comment]
Hey @ariona !

Thanks for your patience. I've added this feature now. Check it out:

<img width="882" alt="screen shot 2017-04-26 at 15 20 17" src="https://cloud.githubusercontent.com/assets/8677283/25439271/e65bf0d0-2a93-11e7-94c0-15f1bb89fbe3.png">

**Comment by ireade** [comment]
Added in commit [fc706439d3dc3dbb32e90d5d8a8ba34894a13cb8](https://github.com/ireade/caniuse-embed/commit/fc706439d3dc3dbb32e90d5d8a8ba34894a13cb8)
