### ISSUE TITLE
Description error

### ISSUE THREAD

**Issue by ManzDev** [ireade/caniuse-embed#3]
For URL of "menu" tag with description `Method of defining a toolbar menu, a context menu or a list of (interactive) options using the <menu> element.` The "menu" tag from description render like as tag instead text:

► http://caniuse.com/#feat=menu
► http://caniuse.bitsofco.de/embed/index.html?feat=menu&periods=future_2,future_1,current,past_1,past_2

**Comment by ireade** [comment]
Thanks for letting me know about this, will fix asap!

**Comment by ireade** [comment]
@ManzDev It's been fixed in the latest update ([eff81249e356e773d7ba0cba8ea71389e0a5af21](eff81249e356e773d7ba0cba8ea71389e0a5af21)). Thanks!
