### ISSUE TITLE
IE looong space

### ISSUE THREAD

**Issue by ManzDev** [ireade/caniuse-embed#4]
Internet Explorer v11.240.10586.0 / Win10

On link, IE shows a looong space. On iframe, page make a "infinite" scroll...

Link: http://caniuse.bitsofco.de/embed/index.html?feat=meter&periods=future_2,future_1,current,past_1,past_2

![ie-caniuse-embed](https://cloud.githubusercontent.com/assets/1507150/15094509/f1489b2c-149d-11e6-84cf-848d387d0ac5.gif)

**Comment by ireade** [comment]
Thanks, is that only on that particular feature or is it the same for all features in IE?

**Comment by ManzDev** [comment]
Same error in all features.

**Comment by ManzDev** [comment]
I understand that SVG is a icon for links. With a style="max-height:20px" over SVG html tag, fix it for all browsers.

**Comment by ireade** [comment]
Hi @ManzDev . I've (finally) gotten around to pushing an update that should fix this issue. Please let me know if it's working now.

**Comment by ManzDev** [comment]
Fixed on IE 11.1066.14393.0 / Win10
