### ISSUE TITLE
Infinite height glitch on safari (5x and below)

### ISSUE THREAD

**Issue by JoshuaSand0val** [ireade/caniuse-embed#5]
Hey, I really like this plugin, but there's a serious issue with it: on Safari 5 (maybe 6) and below, the height of the iframe glitches out and becomes infinite breaking my page. There's also a scrolling glitch but that's not really an issue that has to be addressed. If you don't have safari 5 on your PC, apple still hosts the link here: http://appldnld.apple.com/Safari5/041-5487.20120509.INU8B/SafariSetup.exe

![capture](https://cloud.githubusercontent.com/assets/22820141/19356592/f339fa9e-9133-11e6-9335-0a7c987d20c3.JPG)

**Comment by ireade** [comment]
Hi @JoshuaSand0val . Unfortunately, I can't support as far back as Safari 5. According to caniuse itself, that browser is less than 0.05 percent of global use.

**Comment by JoshuaSand0val** [comment]
That's too bad, however… I believe you actually accidentally fixed the bug. I checked a few days ago, and it wasn't happening (at least on my webpage).

**Comment by ireade** [comment]
Ah awesome! I think I know what may have caused the bug then. It was the svg icon I was using that didn't have a set height.
