### ISSUE TITLE
Update featured 10 browsers?

### ISSUE THREAD

**Issue by poshaughnessy** [ireade/caniuse-embed#7]
Hi! A little while ago, caniuse.com updated the default view of 10 to display UC Browser and Samsung Internet (disclaimer: where I work). This is due to the [StatCounter data](http://gs.statcounter.com/) showing that they have more global usage than Opera Desktop and the stock Android browser (the two which were bumped).

Currently, StatCounter has UC Browser as number 3 globally and Samsung Internet as number 6 globally (and one higher at number 5, when just considering the mobile category).

Please might you consider making the same update for caniuse-embed? :)

**Comment by ireade** [comment]
Done - https://github.com/ireade/caniuse-embed/commit/fc7d8f60a82533f2c35adb5fcf75da27e13f1441

**Comment by poshaughnessy** [comment]
Great, thanks @ireade!
