### ISSUE TITLE
Borked?

### ISSUE THREAD

**Issue by kaycebasques** [ireade/caniuse-embed#8]
Howdy,

I'm trying to embed the preload data into one of the Lighthouse reference docs.

Using the generated embed code:

```
<script src="https://cdn.jsdelivr.net/gh/ireade/caniuse-embed/caniuse-embed.min.js"></script>
  
<p class="ciu_embed" data-feature="link-rel-preload"
   data-periods="future_2,future_1,current,past_1,past_2"
   data-accessible-colours="false">
  <a href="http://caniuse.com/#feat=link-rel-preload">Can I Use link-rel-preload?</a>
  Data on support for the link-rel-preload feature across the major browsers from caniuse.com.
</p>
```

Doesn't seem to be working. Just displays the plaintext, without the fancy table.

**Comment by ireade** [comment]
Hi @kaycebasques !

Looking at your screenshot, it doesn't seem like the embed script is in there. Is this script on the page?

```html
<script src="https://cdn.jsdelivr.net/gh/ireade/caniuse-embed/caniuse-embed.min.js"></script>
```

**Comment by kaycebasques** [comment]
Hallo,

The first screenshot did have the embed script (in the `head`). Let me put something up on Glitch and see if I can reproduce...

**Comment by kaycebasques** [comment]
Problem was that I was declaring the script before the embed element. Putting the script after the embed element solved it. Seems a little fragile?

**Comment by kaycebasques** [comment]
FYI I'm gonna use the embed in the Lighthouse docs, if I can get it display correctly! (Nothing to do on your side, it's just a matter of getting the embed to play nicely with our infrastructure)

**Comment by ireade** [comment]
> Problem was that I was declaring the script before the embed element. Putting the script after the embed element solved it. Seems a little fragile?

Ah I see! Yes I should improve on that to allow the script to be placed anywhere, I'll work on that.

> FYI I'm gonna use the embed in the Lighthouse docs, if I can get it display correctly! (Nothing to do on your side, it's just a matter of getting the embed to play nicely with our infrastructure)

Awesome! Let me know if there's anything I can do to improve the embed :)

**Comment by ireade** [comment]
This is now fixed, the main script only runs after `DOMContentLoaded` https://github.com/ireade/caniuse-embed/blob/gh-pages/src/caniuse-embed.js#L2

**Comment by kaycebasques** [comment]
Wonderful, thank you!
